//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.8.100
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1078 with alias "hasComponents"
	/// <summary>_HasComponents</summary>
	public partial interface IHasComponents : IPublishedContent
	{
		/// <summary>Components</summary>
		IEnumerable<IPublishedContent> Components { get; }
	}

	/// <summary>_HasComponents</summary>
	[PublishedContentModel("hasComponents")]
	public partial class HasComponents : PublishedContentModel, IHasComponents
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "hasComponents";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HasComponents(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HasComponents, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Components
		///</summary>
		[ImplementPropertyType("components")]
		public IEnumerable<IPublishedContent> Components
		{
			get { return GetComponents(this); }
		}

		/// <summary>Static getter for Components</summary>
		public static IEnumerable<IPublishedContent> GetComponents(IHasComponents that) { return that.GetPropertyValue<IEnumerable<IPublishedContent>>("components"); }
	}
}
