//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.8.100
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1110 with alias "hasRenderOptions"
	/// <summary>_HasRenderOptions</summary>
	public partial interface IHasRenderOptions : IPublishedContent
	{
		/// <summary>Render as</summary>
		MBran.Components.PropertyEditors.RenderOptions.RenderOption RenderOption { get; }
	}

	/// <summary>_HasRenderOptions</summary>
	[PublishedContentModel("hasRenderOptions")]
	public partial class HasRenderOptions : PublishedContentModel, IHasRenderOptions
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "hasRenderOptions";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HasRenderOptions(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HasRenderOptions, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Render as
		///</summary>
		[ImplementPropertyType("renderOption")]
		public MBran.Components.PropertyEditors.RenderOptions.RenderOption RenderOption
		{
			get { return GetRenderOption(this); }
		}

		/// <summary>Static getter for Render as</summary>
		public static MBran.Components.PropertyEditors.RenderOptions.RenderOption GetRenderOption(IHasRenderOptions that) { return that.GetPropertyValue<MBran.Components.PropertyEditors.RenderOptions.RenderOption>("renderOption"); }
	}
}
